name: ios

on:
  push:
    branches:
      - main  # Change this if you want it to trigger on a different branch
  pull_request:
    branches:
      - main  # Change this if you want it to trigger on pull requests
  workflow_dispatch:

jobs:
  upload_to_testflight:
    runs-on: macos-latest  # Use macOS runner for uploading to TestFlight

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout your repository so we can access the files

      - name: Set up Ruby (required for Fastlane or using altool)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install fastlane  # Optional: Install fastlane if you need it
          brew install cocoapods  # Optional: If you use CocoaPods

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app -f app-v1.ipa -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APPLE_PASSWORD }}
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
